/**
 * \file nvmops.c
 * \brief Functions to use the Non Volatile Memory.
 *
 * \copyright Copyright (c) 2018 Infineon Technologies AG. All rights reserved.
 *
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 */

/* IFX includes */
#include "Cpu/Std/Platform_Types.h"
#include "Cpu/Std/Ifx_Types.h"
#include "Cpu/Std/IfxCpu.h"

/* Application includes */
#include "nvmops.h"

#define MEM *(volatile uint32*)

uint32 pflash_erase(uint32 addr, uint32 cnt)
{
	volatile uint32 pmuid;

	if (cnt >= 32)
		return (1);

	// Clear the Erase State Flag DMU_HF_OPERATION.ERASE
	//DMU_HF_CONTROL.B.CERASE = 1;

    // Clear Status
	MEM (0xAF005554) = 0xFA;
	pmuid = PMU_ID.U;

	// Erase Logical Sector Range
	MEM (0xAF00AA50) = (uint32) addr;
	pmuid = PMU_ID.U;
	MEM (0xAF00AA58) = (uint32) cnt;
	pmuid = PMU_ID.U;
	MEM (0xAF00AAA8) = (uint32) 0x80;
	pmuid = PMU_ID.U;
	MEM (0xAF00AAA8) = (uint32) 0x50;
	pmuid = PMU_ID.U;

	while(!DMU_HF_OPERATION.B.ERASE);
	while(DMU_HF_STATUS.B.D0BUSY); // ToDo

	return (0);
}

uint32 dflash_erase(uint32 addr, uint32 cnt)
{
	volatile uint32 pmuid;

	if (cnt >= 64)
		return (1);

	// Clear the Erase State Flag DMU_HF_OPERATION.ERASE
	//DMU_HF_CONTROL.B.CERASE = 1;

    // Clear Status
	MEM (0xAF005554) = 0xFA;
	pmuid = PMU_ID.U;

	// Erase Logical Sector Range
	MEM (0xAF00AA50) = (uint32) addr;
	pmuid = PMU_ID.U;
	MEM (0xAF00AA58) = (uint32) cnt;
	pmuid = PMU_ID.U;
	MEM (0xAF00AAA8) = (uint32) 0x80;
	pmuid = PMU_ID.U;
	MEM (0xAF00AAA8) = (uint32) 0x50;
	pmuid = PMU_ID.U;

	while(!DMU_HF_OPERATION.B.ERASE);
	while(DMU_HF_STATUS.B.D0BUSY);

	return (0);
}

uint32 ucb_erase(uint32 addr)
{
	volatile uint32 pmuid;

	// Clear the Erase State Flag DMU_HF_OPERATION.ERASE
	//DMU_HF_CONTROL.B.CERASE = 1;

    // Clear Status
	MEM (0xAF005554) = 0xFA;
	pmuid = PMU_ID.U;

	// Erase Logical Sector Range
	MEM (0xAF00AA50) = (uint32) addr;
	pmuid = PMU_ID.U;
	MEM (0xAF00AA58) = (uint32) 1;
	pmuid = PMU_ID.U;
	MEM (0xAF00AAA8) = (uint32) 0x80;
	pmuid = PMU_ID.U;
	MEM (0xAF00AAA8) = (uint32) 0x50;
	pmuid = PMU_ID.U;

	while(!DMU_HF_OPERATION.B.ERASE);
	while(DMU_HF_STATUS.B.D0BUSY);

	return (0);
}

void ucb_dflash_burst_program(uint32 addr, uint32 *pmem)
{
	volatile uint32 i;
	volatile uint32 low32bit, high32bit;
	volatile uint32 pmuid;

	// Clear the Erase State Flag DMU_HF_OPERATION.ERASE
	//DMU_HF_CONTROL.B.CERASE = 1;

	// Clear Status
	MEM (0xAF005554) = 0xFA;
	pmuid = PMU_ID.U;

	// Enter Page Mode DFLASH
	MEM (0xAF005554) = 0x5D;
	pmuid = PMU_ID.U;

	// Load Page
	i = 0;
	while (i < 8) // 4 * 8 byte = 32 byte
	{
		low32bit = pmem[i];  //load page
		high32bit = pmem[i + 1];
		MEM (0xAF0055F0) = low32bit;
		pmuid = PMU_ID.U;
		MEM (0xAF0055F4) = high32bit;
		pmuid = PMU_ID.U;
		i += 2;
	}

	while(DMU_HF_STATUS.B.D0BUSY);

	// Write Burst
	MEM (0xAF00AA50) = (uint32) addr;
	pmuid = PMU_ID.U;
	MEM (0xAF00AA58) = (uint32) 0x00;
	pmuid = PMU_ID.U;
	MEM (0xAF00AAA8) = (uint32) 0xA0;
	pmuid = PMU_ID.U;
	MEM (0xAF00AAA8) = (uint32) 0xA6;
	pmuid = PMU_ID.U;
	while(!DMU_HF_OPERATION.B.PROG);
	while(DMU_HF_STATUS.B.D0BUSY);
}

void ucb_dflash_page_program(uint32 addr, uint32 lword, uint32 hword)
{
	volatile uint32 pmuid;

	// Clear the Erase State Flag DMU_HF_OPERATION.ERASE
	//DMU_HF_CONTROL.B.CERASE = 1;

	// Clear Status
	MEM (0xAF005554) = 0xFA;
	pmuid = PMU_ID.U;

	// Enter Page Mode DFLASH
	MEM (0xAF005554) = 0x5D;
	pmuid = PMU_ID.U;

	// Load Page
	MEM (0xAF0055F0) = lword;
	pmuid = PMU_ID.U;
	MEM (0xAF0055F4) = hword;
	pmuid = PMU_ID.U;

	while(DMU_HF_STATUS.B.D0BUSY);

	// Write Page
	MEM (0xAF00AA50) = (uint32) addr;
	pmuid = PMU_ID.U;
	MEM (0xAF00AA58) = (uint32) 0x00;
	pmuid = PMU_ID.U;
	MEM (0xAF00AAA8) = (uint32) 0xA0;
	pmuid = PMU_ID.U;
	MEM (0xAF00AAA8) = (uint32) 0xAA;
	pmuid = PMU_ID.U;
	while(!DMU_HF_OPERATION.B.PROG);
	while(DMU_HF_STATUS.B.D0BUSY);
}

void pflash_burst_program(uint32 addr, uint32 *pmem)
{
	volatile uint32 i;
	volatile uint32 low32bit, high32bit;
	volatile uint32 pmuid;

	// Clear the Erase State Flag DMU_HF_OPERATION.ERASE
	//DMU_HF_CONTROL.B.CERASE = 1;

	// Clear Status
	MEM (0xAF005554) = 0xFA;
	pmuid = PMU_ID.U;

	// Enter Page Mode DFLASH
	MEM (0xAF005554) = 0x5D;
	pmuid = PMU_ID.U;

	// Load Page
	i = 0;
	while (i < 64) // 32 * 8 byte = 256 byte
	{
		low32bit = pmem[i];  //load page
		high32bit = pmem[i + 1];
		MEM (0xAF0055F0) = low32bit;
		pmuid = PMU_ID.U;
		MEM (0xAF0055F4) = high32bit;
		pmuid = PMU_ID.U;
		i += 2;
	}

	while(DMU_HF_STATUS.B.D0BUSY);

	// Write Burst
	MEM (0xAF00AA50) = (uint32) addr;
	pmuid = PMU_ID.U;
	MEM (0xAF00AA58) = (uint32) 0x00;
	pmuid = PMU_ID.U;
	MEM (0xAF00AAA8) = (uint32) 0xA0;
	pmuid = PMU_ID.U;
	MEM (0xAF00AAA8) = (uint32) 0xA6;
	pmuid = PMU_ID.U;
	while(!DMU_HF_OPERATION.B.PROG);
	while(DMU_HF_STATUS.B.D0BUSY);
}

void pflash_page_program(uint32 addr, uint32 *pmem)
{
	// Not implemented
}

