/**
 * \file smu_alarms.c
 * \brief Functions to control SMU.
 *
 * \copyright Copyright (c) 2018 Infineon Technologies AG. All rights reserved.
 *
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 */


/* IFX includes */
#include "Cpu/Std/Platform_Types.h"
#include "Cpu/Std/Ifx_Types.h"
#include "Cpu/Std/IfxCpu.h"
#include "Smu/Std/IfxSmu.h"
#include "Src/Std/IfxSrc.h"

/* Macro to define Interrupt Priority */
#define ISR_PRIORITY_SMU_INT0				5

/* Macro to define Interrupt Service Routine */
IFX_INTERRUPT(ISR_SMU, 0, ISR_PRIORITY_SMU_INT0);

/* Interrupt Service Routine of SMU, gets triggered when SMU Software Alarm 0 is triggered */
void ISR_SMU(void)
{
	// Get the alarm source by evaluating the Alarm status register (AGi)
	if(IfxSmu_getAlarmStatus(IfxSmu_Alarm_XBAR_SOTA_SwapError) == TRUE)
	{
		// Actions for SWAP Error Alarm
	    IfxSmu_clearAlarmStatus(IfxSmu_Alarm_XBAR_SOTA_SwapError);                      /* Clear alarm status flag */
	    //showSWAPAlarmStateByLEDs();
	}
	else if(IfxSmu_getAlarmStatus(IfxSmu_Alarm_CPU0_PFI0_PFLASH0_ReadPathError) == TRUE)
	{
		// Actions for PFI Alarm
	    IfxSmu_clearAlarmStatus(IfxSmu_Alarm_CPU0_PFI0_PFLASH0_ReadPathError);          /* Clear alarm status flag */
	    //showPFIAlarmStateByLEDs();
	}

    while(1)
    { }

}

/* This function enables the SWAP related SMU alarms - CPU0 alarm and SRI-Bridge alarm */
void enable_smu_alarms()
{
    /* Enable the SMU register configuration by setting the CFGLCK field of the SMU_KEYS register to 0xBC */
    IfxSmu_unlockConfigRegisters();

    IfxSmu_ConfigureInterruptGeneration(IfxSmu_InterruptGenerationConfiguration_0, IfxSmu_InterruptRequest_0);

    /* React on both Alarms */
    IfxSmu_setAlarmAction(IfxSmu_Alarm_CPU0_PFI0_PFLASH0_ReadPathError, IfxSmu_InternalAlarmAction_igcs0);
    IfxSmu_setAlarmAction(IfxSmu_Alarm_XBAR_SOTA_SwapError,             IfxSmu_InternalAlarmAction_igcs0);

    /* Afterwards, lock the SMU configuration */
    IfxSmu_lockConfigRegisters();

    /* Service request configuration */
    /* Get source pointer of SMU Service Request 0 in order to initialize Interrupt Router */
    volatile Ifx_SRC_SRCR *src = IfxSmu_getSrcPointer(0);
    IfxSrc_init(src, IfxSrc_Tos_cpu0, (Ifx_Priority)ISR_PRIORITY_SMU_INT0);
    IfxSrc_enable(src);

    /* Sets SMU in Run-State */
    IfxSmu_activateRunState();
}

