/**
 * \file swap.c
 * \brief Functions to perform the SWAP.
 *
 * \copyright Copyright (c) 2018 Infineon Technologies AG. All rights reserved.
 *
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 */


#include "swap.h"
#include "nvmops.h"

#define UCB_OTP0_ORIG   0xAF404000
#define SWAP_EN_CODE    0x00030000
#define UCB_SWAP_ORIG   0xAF402E00
#define UCB_SWAP_COPY   0xAF403E00
#define UNLOCKCODE      0x43211234
#define CONFIRMEDCODE   0x57b5327f
#define ZEROS           0x00000000



void enable_swap()
{
	// If Swap is off then enable
	if(!(SCU_STMEM1.U & 0x00030000))
	{
		/* Ray: Page 468( HF_PROCONTP ), Enable SOTA mode */
		ucb_dflash_page_program(UCB_OTP0_ORIG + 0x1E8, SWAP_EN_CODE, ZEROS);
	}
}

void disable_swap()
{
    ucb_erase(UCB_OTP0_ORIG);
    ucb_dflash_page_program(UCB_OTP0_ORIG + 0x1f0, UNLOCKCODE   , ZEROS);
}

void configure_swap(uint32 map)
{
	uint32 nxtfreeswapidx;
	uint32 nxtfreeswapadr;

	// If SWAP is off OR a swap config on pos 15 exists evaluating SCU_STMEM1 register
	if((SCU_STMEM1.U & 0x00030000) == 0 || ((SCU_STMEM1.U & 0x00f80000) >> 3) == 0x001e0000)
	{
		// Erase and write initial swap config to _COPY
	    ucb_erase(UCB_SWAP_COPY);
	    ucb_dflash_page_program(UCB_SWAP_COPY        , map          , UCB_SWAP_COPY);
	    ucb_dflash_page_program(UCB_SWAP_COPY + 8    , CONFIRMEDCODE, UCB_SWAP_COPY + 8);
	    ucb_dflash_page_program(UCB_SWAP_COPY + 0x1f0, UNLOCKCODE   , ZEROS);
	    // Erase and write initial swap config to _ORIG
	    ucb_erase(UCB_SWAP_ORIG);
	    ucb_dflash_page_program(UCB_SWAP_ORIG        , map          , UCB_SWAP_ORIG);
	    ucb_dflash_page_program(UCB_SWAP_ORIG + 8    , CONFIRMEDCODE, UCB_SWAP_ORIG + 8);
	    ucb_dflash_page_program(UCB_SWAP_ORIG + 0x1f0, UNLOCKCODE   , ZEROS);
	}
	// add a new swap config to next free index
	else
	{
		// Compute next free index based on SCU_STMEM1 register
		nxtfreeswapidx = (((SCU_STMEM1.U & 0x00f80000) >> 20) + 1) * 0x10;
		nxtfreeswapadr = UCB_SWAP_COPY + nxtfreeswapidx;
		// Add swap config to UCB_SWAP_COPY
	    ucb_dflash_page_program(nxtfreeswapadr, map, nxtfreeswapadr);
	    ucb_dflash_page_program(nxtfreeswapadr + 8, CONFIRMEDCODE, nxtfreeswapadr + 8);
	    // Add swap config to UCB_SWAP_ORIG
		nxtfreeswapadr = UCB_SWAP_ORIG + nxtfreeswapidx;
	    ucb_dflash_page_program(nxtfreeswapadr, map, nxtfreeswapadr);
	    ucb_dflash_page_program(nxtfreeswapadr + 8, CONFIRMEDCODE, nxtfreeswapadr + 8);
	}
}

void do_swap( void )
{
   enable_swap();
	switch((SCU_STMEM1.U & 0x00030000) >> 16)
	{
		case 0: // Coming from SWAP disabled state - the function 'enable_swap()' enables SWAP and SWAP becomes active after the next SystemReset.
				// This case installs a initial SWAP configuration to prevent the device from getting locked. See App Note for further details.
			configure_swap(0x55);
			break;
		case 1: // In case group of A-Banks are installed by SSW, config B-Banks to become active after next system reset.
			configure_swap(0xaa);
			break;
		case 2: // In case group of B banks are installed by SSW, config A-Banks to become active after next system reset.
			configure_swap(0x55);
			break;
		default:
			configure_swap(0x55);
			break;
	}
}

uint8 get_currentBank( void )
{
	uint8 a_bank = 0x55;
	uint8 b_bank = 0xaa;


	switch((SCU_STMEM1.U & 0x00030000) >> 16)
	{
		case 0: // Coming from SWAP disabled state - the function 'enable_swap()' enables SWAP and SWAP becomes active after the next SystemReset.
				// This case installs a initial SWAP configuration to prevent the device from getting locked. See App Note for further details.
			return( a_bank );
		case 1: // In case group of A-Banks are installed by SSW, config B-Banks to become active after next system reset.
			return( a_bank );
		case 2: // In case group of B banks are installed by SSW, config A-Banks to become active after next system reset.
			return( b_bank );
		default:
			return( a_bank );
	}
}

