/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
  *********************************************************************************************************************/
 /*\title TC375 FreeRTOS basic example
 * \abstract This example shows how to get started with using the AURIX(TM) FreeRTOS port
 * \description This example explores FreeRTOS usage on AURIX(TM) TC375 using two simple tasks and one interrupt
 *
 * \name iLLD_TC375_ADS_FreeRTOS_Basic
 * \version V1.0.0
 * \board AURIX TC375 lite Kit, KIT_A2G_TC375_LITE, TC37xTP_A-Step
 * \keywords AURIX, TC3XX, TC375, FreeRTOS, Blinky, Task, ERU, LED, Button, External Interrupt
 * \documents See README.md
 * \lastUpdated 2023-04-27
 *********************************************************************************************************************/
#include <IfxCpu.h>
#include <IfxFlash.h>
#include <IfxScuWdt.h>
#include <FreeRTOS.h>
#include <task.h>

#include "comm.h"
#include "shell.h"
#include "GETH_OS.h"
#include "eeprom.h"
#include "board.h"
#include "led.h"
#include "can.h"
#include "isouart.h"
#include "ecu8tr_net.h"
#include "ecu8tr_can.h"
#include "bq79600.h"

IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

void core0_main(void)
{
	IfxCpu_enableInterrupts();

	/* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
	 * Enable the watchdogs and service them periodically if it is required
	 */
	IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
	IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

	/* Wait for CPU sync event */
	IfxCpu_emitEvent(&g_cpuSyncEvent);
	IfxCpu_waitEvent(&g_cpuSyncEvent, 10);


#if 0
	disable_swap();

	PRINTF( "The swap is disabled\n" );

	while( 1 )
		;
#endif

#if 0
	void pfls_MassErase( uint32 start_address );
	pfls_MassErase();
#endif


	eeprom_read_net_config();
	eeprom_read_tle9012_conf();
	gpio_init();
	start_led();

	start_can();
	start_network();
#if __TI__
#else
	isouart_init();
#endif

#if !__TI__
	ecu8tr_canServerInit();
#endif
    ecu8_tcpServerInit();
    ecu8_udpServerInit();
    bq79600_taskInit();

    /* Start the scheduler */
    vTaskStartScheduler();
    
    while (1)
    {
    }
}



/* Required FreeRTOS callback, called in case of a stack overflow.
 * For the sake of simplicity, this function will loop indefinitely
 * and the root cause can be confirmed by using a debugger
 */
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    while (1)
    {
        __nop();
    }
}
