/**********************************************************************************************************************
 * \file Cpu2_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include <IfxStm.h>
#include "IfxScuWdt.h"
#include "shell.h"
#include "bq79600.h"
#include "bq_shared.h"
#include "led.h"

extern IfxCpu_syncEvent g_cpuSyncEvent;
extern ECU8TR_CAN_STATUS_e ecu8tr_can_status;

static void delay_us(uint32 us)
{
    uint64 ticks = IfxStm_getTicksFromMicroseconds(&MODULE_STM2, us);
    IfxStm_waitTicks( &MODULE_STM2, ticks );
}

static void delay_ms(uint32 ms)
{
    delay_us(ms * 1000);
}

#if 1
static void BQ_UpdateVoltages(uint16 cellRaw[TOTALBOARDS-1][TI_NUM_CELL], uint16 tempRaw[TOTALBOARDS-1][TI_NUM_GPIOADC] )
{
    // Step 1: Write all cell voltages
	for( uint8 board = 0; board < (TOTALBOARDS-1); board++ )
	{
		for (uint8 cell = 0; cell < TI_NUM_CELL; cell++)
			g_bqSharedData.cellVolt[board][cell] = cellRaw[board][cell];
		for (uint8 cell = 0; cell < TI_NUM_GPIOADC; cell++)
			g_bqSharedData.cellTemp[board][cell] = tempRaw[board][cell];
	}

    // Step 2: Optional timestamp
    g_bqSharedData.timestamp = 0;

    // Step 3: Memory barrier before flag set
    __dsync();   // Ensure all data is written before flag update

    // Step 4: Set flag last
    g_bqSharedData.dataReady = 1;
}
#else
static void BQ_UpdateVoltages(uint16 cellRaw[TOTALBOARDS-1][TI_NUM_CELL] )
{

}
#endif


void core2_main(void)
{

    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG2 IS DISABLED HERE!!
     * Enable the watchdog and service it periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    

    ////PRINTF( "This is a hello from CORE2\r\n" );
    //PRINTF( "This is a bootloader tester*************\r\n" );


    delay_ms( 1000 );
    bq79xxx_comInit();

	if( 0 == bq79xxx_doInit_Rev() )
	{
		PRINTF( "BQ79600: Auto Addressing in Reverse way.\r\n" );
	}
	else if( 0 == bq79xxx_doInit() )
	{
		PRINTF( "BQ79600: Auto Addressing in forward way.\r\n" );
	}
	else
	{
	    uint8 is_connected = 0;

	    while( is_connected == 0 )
	    {
            PRINTF( "Failed to talk to BQ79600, please check the connection\r\n" );
            delay_ms( 1000 );
            if( 0 == bq79xxx_doInit_Rev() )
            {
                PRINTF( "BQ79600: Auto Addressing in Reverse way.\r\n" );
                is_connected = 1;
            }
            else if( 0 == bq79xxx_doInit() )
            {
                PRINTF( "BQ79600: Auto Addressing in forward way.\r\n" );
                is_connected = 1;
            }
	    }
	}

	ecu8tr_can_status = ECU8TR_CAN_TLE9012_WAKEUP;

    while(1)
    {
    	static uint16 count = 0;
    	static uint16 volt[TOTALBOARDS-1][TI_NUM_CELL] = {{0}};
    	static uint16 gpio[TOTALBOARDS-1][TI_NUM_GPIOADC] = {{0}};

        bq79xxx_sampleVolt( volt );
        if( count++ == 2)
        {
        	count = 0;
        	bq79xxx_sampleGPIO( gpio );
        }
        BQ_UpdateVoltages( volt, gpio );

        delay_ms( 1000 * 1 ); //delay 1 seconds
    }
}
