/**
 * \file nvmops.h
 * \brief Functions to use the Non Volatile Memory.
 *
 * \copyright Copyright (c) 2018 Infineon Technologies AG. All rights reserved.
 *
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 */

#ifndef SRC_APPSW_TRICORE_NVMOPS_H
#define SRC_APPSW_TRICORE_NVMOPS_H

/* IFX includes */
#include "Cpu/Std/Platform_Types.h"
#include "Cpu/Std/Ifx_Types.h"
#include "Cpu/Std/IfxCpu.h"
#include "Ifx_reg.h"

/*!
 * \brief Start to Erase the Program Flash at the given address.
 */
extern uint32 pflash_erase(uint32 addr, uint32 cnt);

/*!
 * \brief Start to Erase the Data Flash at the given address.
 */
extern uint32 dflash_erase(uint32 addr, uint32 cnt);

/*!
 * \brief Start to Erase the UCB Flash at the given address.
 */
extern uint32 ucb_erase(uint32 addr);

/*!
 * \brief Program a 32byte Page to a given address of Data Flash.
 */
extern void ucb_dflash_burst_program(uint32 addr, uint32 *pmem);

/*!
 * \brief Program a 32byte Page to a given address of Data Flash and UCB.
 */
extern void ucb_dflash_page_program(uint32 addr, uint32 lword, uint32 hword);

/*!
 * \brief Program a 256byte Page to a given address of Data Flash.
 */
extern void pflash_burst_program(uint32 addr, uint32 *pmem);

/*!
 * \brief Program a 256byte Page to a given address of Data Flash.
 */
extern void pflash_page_program(uint32 addr, uint32 *pmem);

#endif /* SRC_APPSW_TRICORE_NVMOPS_H */
