/*
 * shell.c
 *
 *  Created on: Jan 22, 2024
 *      Author: rgeng
 */


/**********************************************************************************************************************
 * \file ASCLIN_Shell_UART.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <bsp/inc/ecu8tr_global.h>
#include <stdio.h>
#include <stdarg.h>
#include <Ifx_Types.h>
#include <IfxAsclin_Asc.h>
#include <Ifx_Shell.h>
#include <Ifx_Console.h>
#include <IfxPort.h>
#include <FreeRTOS.h>
#include <FreeRTOSConfig.h>
#include <IfxGeth_Eth.h>

#include "ecu8tr_version.h"
#include "isouart.h"
#include "tle9012.h"
#include "shell.h"
#include "comm.h"
#include "eeprom.h"
#include "board.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* Communication parameters */
#define ISR_PRIORITY_ASCLIN_TX      8                                       /* Priority for interrupt ISR Transmit  */
#define ISR_PRIORITY_ASCLIN_RX      4                                       /* Priority for interrupt ISR Receive   */
#define ISR_PRIORITY_ASCLIN_ER      12                                      /* Priority for interrupt ISR Errors    */
#define ASC_TX_BUFFER_SIZE          256                                     /* Define the TX buffer size in byte    */
#define ASC_RX_BUFFER_SIZE          256                                     /* Define the RX buffer size in byte    */
#define ASC_BAUDRATE                115200                                  /* Define the UART baud rate            */


/* Shell commands and help descriptions */
#define COMMAND_INFO                "info"
#define COMMAND_HELP                "help"

#define COMMAND_INFO_HELP_TEXT      "   : Show the info"
#define COMMAND_HELP_HELP_TEXT      "   : Show this help list"

#define COMMAND_SET_DHCP			"set_dhcp"
#define COMMAND_SET_MAC				"set_mac"
#define COMMAND_SET_IP				"set_ip"
#define COMMAND_SET_NETMASK			"set_netmask"
#define COMMAND_SET_GATEWAY			"set_gateway"
#define COMMAND_SHOW_NETWORK		"show_network"
#define COMMAND_SHOW_LINK			"show_link"
#define COMMAND_SHOW_VERSION		"show_version"
#define COMMAND_SHOW_ISOUART		"show_isouart"
#define COMMAND_SHOW_BITWIDTH		"show_bitwidth"
#define COMMAND_RESET				"reset"
#define COMMAND_BQ_SLEEP			"bq_sleep"
#define COMMAND_BQ_WAKE				"bq_wake"


#define COMMAND_SET_DHCP_HELP_TEXT		"   : enable/disable DHCP( set_dhcp 1: enable; set_dhcp 0: disable )"
#define COMMAND_SET_MAC_HELP_TEXT		"   : set the box's MAC address( 0c:0a:0b:03:04:05 )"
#define COMMAND_SET_IP_HELP_TEXT		"   : set the box's IP address( 192.168.1.100 )"
#define COMMAND_SET_NETMASK_HELP_TEXT	"   : set the box's netmask( 255.255.255.0 )"
#define COMMAND_SET_GATEWAY_HELP_TEXT	"   : set the box's gateway IP address( 192.168.1.1 )"
#define COMMAND_SHOW_NETWORK_HELP_TEXT	"   : Show network configuration"
#define COMMAND_SHOW_LINK_HELP_TEXT		"   : Show PHY link speed & duplex"
#define COMMAND_SHOW_VERSION_HELP_TEXT	"   : Show the firmware version"
#define COMMAND_SHOW_ISOUART_HELP_TEXT	"   : Show the ISOUART network"
#define COMMAND_RESET_TEXT				"   : reset the box"
#define COMMAND_SHOW_BITWIDTH_HELP_TEXT	"   : Show the tle9012 ADC bit width"
#define COMMAND_BQ_SLEEP_TEXT			"	: Put BQ79600 into sleep mode"
#define COMMAND_BQ_WAKE_TEXT			"	: Put BQ79600 into wake mode"

/*********************************************************************************************************************/
/*------------------------------------------------External Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
extern void GETH_OS_get_link_info( char *p_info );


/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void initSerialInterface(void);
void printInfo( IfxStdIf_DPipe *io );
boolean printShellInfo(pchar args, void *data, IfxStdIf_DPipe *io);
boolean set_mac(pchar args, void *data, IfxStdIf_DPipe *io);
boolean set_ip(pchar args, void *data, IfxStdIf_DPipe *io);
boolean set_netmask(pchar args, void *data, IfxStdIf_DPipe *io);
boolean set_gateway(pchar args, void *data, IfxStdIf_DPipe *io);
boolean show_network(pchar args, void *data, IfxStdIf_DPipe *io);
boolean show_link(pchar args, void *data, IfxStdIf_DPipe *io);
boolean shell_show_version(pchar args, void *data, IfxStdIf_DPipe *io);
boolean shell_reset_board(pchar args, void *data, IfxStdIf_DPipe *io);
boolean set_dhcp(pchar args, void *data, IfxStdIf_DPipe *io);
boolean shell_show_isouart(pchar args, void *data, IfxStdIf_DPipe *io);
boolean shell_show_bitwidth(pchar args, void *data, IfxStdIf_DPipe *io);
boolean shell_bq_sleep( pchar args, void *data, IfxStdIf_DPipe *io );
boolean shell_bq_wake( pchar args, void *data, IfxStdIf_DPipe *io );

extern uint8 bq_cmd;

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxStdIf_DPipe  g_ascStandardInterface;                                     /* Standard interface object            */
IfxAsclin_Asc   g_asclin;                                                   /* ASCLIN module object                 */
Ifx_Shell       g_shellInterface;                                           /* Shell interface object               */

/* The transfer buffers allocate memory for the data itself and for FIFO runtime variables.
 * 8 more bytes have to be added to ensure a proper circular buffer handling independent from
 * the address to which the buffers have been located.
 */
uint8 g_uartTxBuffer[ASC_TX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];
uint8 g_uartRxBuffer[ASC_RX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];

CircularBuffer msg_buffer;


/* Array that stores the supported Shell commands */
const Ifx_Shell_Command g_shellCommands[] =
{
    {COMMAND_INFO,   		COMMAND_INFO_HELP_TEXT,    			&g_shellInterface, &printShellInfo     },
    {COMMAND_HELP,   		COMMAND_HELP_HELP_TEXT,    			&g_shellInterface, &Ifx_Shell_showHelp },
	{COMMAND_SET_DHCP, 		COMMAND_SET_DHCP_HELP_TEXT,  		&g_shellInterface, &set_dhcp },
	{COMMAND_SET_MAC, 		COMMAND_SET_MAC_HELP_TEXT, 			&g_shellInterface, &set_mac },
	{COMMAND_SET_IP, 		COMMAND_SET_IP_HELP_TEXT,  			&g_shellInterface, &set_ip },
	{COMMAND_SET_NETMASK, 	COMMAND_SET_NETMASK_HELP_TEXT,  	&g_shellInterface, &set_netmask },
	{COMMAND_SET_GATEWAY, 	COMMAND_SET_GATEWAY_HELP_TEXT,  	&g_shellInterface, &set_gateway },
	{COMMAND_SHOW_NETWORK, 	COMMAND_SHOW_NETWORK_HELP_TEXT,  	&g_shellInterface, &show_network },
	{COMMAND_SHOW_LINK, 	COMMAND_SHOW_LINK_HELP_TEXT,  		&g_shellInterface, &show_link },
	{COMMAND_SHOW_VERSION, 	COMMAND_SHOW_VERSION_HELP_TEXT,  	&g_shellInterface, &shell_show_version },
	{COMMAND_SHOW_ISOUART, 	COMMAND_SHOW_ISOUART_HELP_TEXT,  	&g_shellInterface, &shell_show_isouart },
	{COMMAND_SHOW_BITWIDTH,	COMMAND_SHOW_BITWIDTH_HELP_TEXT,  	&g_shellInterface, &shell_show_bitwidth },
    {COMMAND_RESET,   		COMMAND_RESET_TEXT,    				&g_shellInterface, &shell_reset_board },
    {COMMAND_BQ_SLEEP, 		COMMAND_BQ_SLEEP_TEXT,    			&g_shellInterface, &shell_bq_sleep },
    {COMMAND_BQ_WAKE,   	COMMAND_BQ_WAKE_TEXT,    			&g_shellInterface, &shell_bq_wake },


    IFX_SHELL_COMMAND_LIST_END
};


/*********************************************************************************************************************/
/*-------------------------------------------------External variables--------------------------------------------------*/
/*********************************************************************************************************************/
extern uint8_t network_def_config[5][8];

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Macro to define Interrupt Service Routine.
 * This macro makes following definitions:
 * 1) Define linker section as .intvec_tc<vector number>_<interrupt priority>.
 * 2) define compiler specific attribute for the interrupt functions.
 * 3) define the Interrupt service routine as ISR function.
 *
 * IFX_INTERRUPT(isr, vectabNum, priority)
 *  - isr: Name of the ISR function.
 *  - vectabNum: Vector table number.
 *  - priority: Interrupt priority. Refer Usage of Interrupt Macro for more details.
 */
IFX_INTERRUPT(asc2TxISR, 0, ISR_PRIORITY_ASCLIN_TX);
void asc2TxISR(void)
{
    IfxStdIf_DPipe_onTransmit(&g_ascStandardInterface);
}

IFX_INTERRUPT(asc2RxISR, 0, ISR_PRIORITY_ASCLIN_RX);

void asc2RxISR(void)
{
    IfxStdIf_DPipe_onReceive(&g_ascStandardInterface);
}

IFX_INTERRUPT(asc2ErrISR, 0, ISR_PRIORITY_ASCLIN_ER);

void asc2ErrISR(void)
{
    IfxStdIf_DPipe_onError(&g_ascStandardInterface);
}

/* Function to print info in the console */
void printInfo(IfxStdIf_DPipe *io)
{
    IfxStdIf_DPipe_print(io, ENDLINE);
    IfxStdIf_DPipe_print(io, "******************************************************************************"ENDLINE);
    IfxStdIf_DPipe_print(io, "Welcome to the NC ECU8-Tester platform.       "ENDLINE);
    IfxStdIf_DPipe_print(io, "******************************************************************************"ENDLINE);

}

boolean shell_bq_sleep( pchar args, void *data, IfxStdIf_DPipe *io )
{
	bq_cmd = 1;
	return TRUE;
}

boolean shell_bq_wake( pchar args, void *data, IfxStdIf_DPipe *io )
{
	bq_cmd = 2;
	return TRUE;
}

boolean shell_show_isouart(pchar args, void *data, IfxStdIf_DPipe *io)
{
	ISOUART_NetArch_t isouart_get_network( void );
	char buffer[16];

	IfxStdIf_DPipe_print( io, ENDLINE );
	sprintf( buffer, "%s\r\n", isouart_get_network()? "HighSide" : "LowSide" );
	IfxStdIf_DPipe_print( io, buffer );
	IfxStdIf_DPipe_print( io, ENDLINE );

	return TRUE;

}

boolean shell_show_bitwidth(pchar args, void *data, IfxStdIf_DPipe *io)
{
	TLE9012_BITWIDTH_t tle9012_getBitWidth( void );
	char buffer[16];

	IfxStdIf_DPipe_print( io, ENDLINE );
	sprintf( buffer, "%s\r\n", (tle9012_getBitWidth()==TLE9012_BITWIDTH_16)? "16bit" : "10bit" );
	IfxStdIf_DPipe_print( io, buffer );
	IfxStdIf_DPipe_print( io, ENDLINE );

	return TRUE;

}


boolean shell_reset_board(pchar args, void *data, IfxStdIf_DPipe *io)
{
	IfxStdIf_DPipe_print( io, ENDLINE );
	IfxStdIf_DPipe_print( io, "Resetting..." );
	IfxStdIf_DPipe_print( io, ENDLINE );
	board_reset( eSysSystem );

	return TRUE;

}

boolean show_network(pchar args, void *data, IfxStdIf_DPipe *io)
{

	IfxStdIf_DPipe_print( io, ENDLINE );
	if( network_def_config[1][4] == 1 )
	{
		IfxStdIf_DPipe_print( io, "DHCP is enabled" );
		IfxStdIf_DPipe_print( io, ENDLINE );
	}
	else
	{
		IfxStdIf_DPipe_print( io, "DHCP is disabled" );
		IfxStdIf_DPipe_print( io, ENDLINE );
	}

	IfxStdIf_DPipe_print( io, "mac address = %02x:%02x:%02x:%02x:%02x:%02x",
			network_def_config[0][0],network_def_config[0][1], network_def_config[0][2], network_def_config[0][3], network_def_config[0][4], network_def_config[0][5] );
	IfxStdIf_DPipe_print( io, ENDLINE );


	IfxStdIf_DPipe_print( io, "ip address = %02d.%02d.%02d.%02d",
			network_def_config[1][0],network_def_config[1][1], network_def_config[1][2], network_def_config[1][3] );
	IfxStdIf_DPipe_print( io, ENDLINE );

	IfxStdIf_DPipe_print( io, "netmask = %02d.%02d.%02d.%02d",
			network_def_config[2][0],network_def_config[2][1], network_def_config[2][2], network_def_config[2][3] );
	IfxStdIf_DPipe_print( io, ENDLINE );

	IfxStdIf_DPipe_print( io, "gateway = %02d.%02d.%02d.%02d",
			network_def_config[3][0],network_def_config[3][1], network_def_config[3][2], network_def_config[3][3] );

	IfxStdIf_DPipe_print( io, ENDLINE );
	IfxStdIf_DPipe_print( io, ENDLINE );

	return TRUE;
}

boolean show_link(pchar args, void *data, IfxStdIf_DPipe *io)
{
	char link_buffer[64];


	IfxStdIf_DPipe_print( io, ENDLINE );
	GETH_OS_get_link_info( link_buffer );
	IfxStdIf_DPipe_print( io, link_buffer );
	IfxStdIf_DPipe_print( io, ENDLINE );
	IfxStdIf_DPipe_print( io, ENDLINE );

	return TRUE;
}

boolean shell_show_version(pchar args, void *data, IfxStdIf_DPipe *io)
{
	char buffer[64];

	sprintf( buffer, "v%d.%d.%d", ECU8TR_MAJOR, ECU8TR_MINIOR, ECU8TR_PATCH );
	IfxStdIf_DPipe_print( io, buffer );

	IfxStdIf_DPipe_print( io, ENDLINE );
	IfxStdIf_DPipe_print( io, ENDLINE );

	return TRUE;
}

boolean set_dhcp(pchar args, void *data, IfxStdIf_DPipe *io)
{
	boolean ret;


	IfxStdIf_DPipe_print( io, ENDLINE );

	if( TRUE == eeprom_set_dhcp( args ) )
	{
	    IfxStdIf_DPipe_print(io, "set dhcp to %s successfully\r\n", args  );
	    ret = TRUE;
	}
	else
	{
		IfxStdIf_DPipe_print(io, "failed to set dhcp\r\n" );
		ret = FALSE;
	}


	IfxStdIf_DPipe_print( io, ENDLINE );

	return ret;

}


boolean set_mac(pchar args, void *data, IfxStdIf_DPipe *io)
{
	boolean ret;


	IfxStdIf_DPipe_print( io, ENDLINE );

	if( TRUE == eeprom_set_mac( args ) )
	{
	    IfxStdIf_DPipe_print(io, "set mac to %s successfully\r\n", args  );
	    ret = TRUE;
	}
	else
	{
		IfxStdIf_DPipe_print(io, "failed to set mac address\r\n" );
		ret = FALSE;
	}


	IfxStdIf_DPipe_print( io, ENDLINE );

	return ret;

}


boolean set_ip(pchar args, void *data, IfxStdIf_DPipe *io)
{
	boolean ret;


	IfxStdIf_DPipe_print( io, ENDLINE );

	if( TRUE == eeprom_set_ip( args ) )
	{
	    IfxStdIf_DPipe_print(io, "set ip to %s successfully\r\n", args  );
	    ret = TRUE;
	}
	else
	{
		IfxStdIf_DPipe_print(io, "failed to set ip address\r\n" );
		ret = FALSE;
	}


	IfxStdIf_DPipe_print( io, ENDLINE );

	return ret;
}

boolean set_netmask(pchar args, void *data, IfxStdIf_DPipe *io)
{
	IfxStdIf_DPipe_print( io, ENDLINE );
	boolean ret;

	if( TRUE == eeprom_set_netmask( args ) )
	{
	    IfxStdIf_DPipe_print(io, "set netmask to %s successfully\r\n", args  );
	    ret = TRUE;
	}
	else
	{
		IfxStdIf_DPipe_print(io, "failed to set netmask address\r\n" );
		ret = FALSE;
	}


	IfxStdIf_DPipe_print( io, ENDLINE );

	return ret;
}


boolean set_gateway(pchar args, void *data, IfxStdIf_DPipe *io)
{
	boolean ret;

	IfxStdIf_DPipe_print( io, ENDLINE );

	if( TRUE == eeprom_set_gateway( args ) )
	{
	    IfxStdIf_DPipe_print(io, "set gateway to %s successfully\r\n", args  );
	    ret = TRUE;
	}
	else
	{
		IfxStdIf_DPipe_print(io, "failed to set gateway address\r\n" );
		ret = FALSE;
	}


	IfxStdIf_DPipe_print( io, ENDLINE );

	return ret;
}


/* Function to show information about the example through the shell */
boolean printShellInfo(pchar args, void *data, IfxStdIf_DPipe *io)
{
    printInfo(io);
    return TRUE;
}

/* Function to initialize ASCLIN module */
void initSerialInterface(void)
{
    IfxAsclin_Asc_Config ascConf;

    /* Set default configurations */
    IfxAsclin_Asc_initModuleConfig( &ascConf, &MODULE_ASCLIN2 ); /* Initialize the structure with default values      */

    /* Set the desired baud rate */
    ascConf.baudrate.baudrate = ASC_BAUDRATE;                                   /* Set the baud rate in bit/s       */
    ascConf.baudrate.oversampling = IfxAsclin_OversamplingFactor_16;            /* Set the oversampling factor      */

    /* Configure the sampling mode */
    ascConf.bitTiming.medianFilter = IfxAsclin_SamplesPerBit_three;             /* Set the number of samples per bit*/
    ascConf.bitTiming.samplePointPosition = IfxAsclin_SamplePointPosition_8;    /* Set the first sample position    */

    /* ISR priorities and interrupt target */
    ascConf.interrupt.txPriority = ISR_PRIORITY_ASCLIN_TX;  /* Set the interrupt priority for TX events             */
    ascConf.interrupt.rxPriority = ISR_PRIORITY_ASCLIN_RX;  /* Set the interrupt priority for RX events             */
    ascConf.interrupt.erPriority = ISR_PRIORITY_ASCLIN_ER;  /* Set the interrupt priority for Error events          */
    ascConf.interrupt.typeOfService = IfxSrc_Tos_cpu0;

    /* Pin configuration */
    const IfxAsclin_Asc_Pins pins = {
            .cts        = NULL_PTR,                         /* CTS pin not used                                     */
            .ctsMode    = IfxPort_InputMode_pullUp,
            .rx         = &IfxAsclin2_RXC_P02_10_IN,         /* Select the pin for RX connected to the USB port      */
            .rxMode     = IfxPort_InputMode_pullUp,         /* RX pin                                               */
            .rts        = NULL_PTR,                         /* RTS pin not used                                     */
            .rtsMode    = IfxPort_OutputMode_pushPull,
            .tx         = &IfxAsclin2_TX_P02_9_OUT,         /* Select the pin for TX connected to the USB port      */
            .txMode     = IfxPort_OutputMode_pushPull,      /* TX pin                                               */
            .pinDriver  = IfxPort_PadDriver_cmosAutomotiveSpeed1
    };

    ascConf.pins = &pins;

    /* FIFO buffers configuration */
    ascConf.txBuffer = g_uartTxBuffer;                      /* Set the transmission buffer                          */
    ascConf.txBufferSize = ASC_TX_BUFFER_SIZE;              /* Set the transmission buffer size                     */
    ascConf.rxBuffer = g_uartRxBuffer;                      /* Set the receiving buffer                             */
    ascConf.rxBufferSize = ASC_RX_BUFFER_SIZE;              /* Set the receiving buffer size                        */

    /* Init ASCLIN module */
    IfxAsclin_Asc_initModule(&g_asclin, &ascConf);          /* Initialize the module with the given configuration   */
}

/* Function to initialize the Shell */
static void initShellInterface(void)
{
    /* Initialize the hardware peripherals */
    initSerialInterface();

    /* Initialize the Standard Interface */
    IfxAsclin_Asc_stdIfDPipeInit(&g_ascStandardInterface, &g_asclin);

    /* Initialize the Console */
    Ifx_Console_init(&g_ascStandardInterface);

    /* Print info to the console */
    printInfo(&g_ascStandardInterface);
    Ifx_Console_print(ENDLINE "Enter '" COMMAND_HELP "' to see the available commands" ENDLINE);

    /* Initialize the shell */
    Ifx_Shell_Config shellConf;
    Ifx_Shell_initConfig(&shellConf);                       /* Initialize the structure with default values         */

    shellConf.standardIo = &g_ascStandardInterface;         /* Set a pointer to the standard interface              */
    shellConf.commandList[0] = &g_shellCommands[0];         /* Set the supported command list                       */

    Ifx_Shell_init(&g_shellInterface, &shellConf);          /* Initialize the Shell with the given configuration    */
}

/* Function to process the incoming received data */
static void runShellInterface(void)
{
    /* Process the received data */
    Ifx_Shell_process(&g_shellInterface);
}



static void initBuffer( void )
{
	msg_buffer.head = 0;
	msg_buffer.tail = 0;
	msg_buffer.count = 0;
}

static bool retrieveMessage( char *message )
{
    if( msg_buffer.count <= 0 )
    {
        // Buffer is empty
        return false;
    }

    strncpy( message, msg_buffer.messages[msg_buffer.tail].data, MAX_MESSAGE_LENGTH);
    memset( msg_buffer.messages[msg_buffer.tail].data, 0, MAX_MESSAGE_LENGTH );
    msg_buffer.tail = (msg_buffer.tail + 1) % BUFFER_SIZE;
    msg_buffer.count--;
    return true;
}

bool insertMessage(const char *format, ... )
{
    if( msg_buffer. count >= BUFFER_SIZE )
    {
        // Buffer is full
        return false;
    }

    va_list args;
    va_start(args, format);
    vsnprintf( msg_buffer.messages[msg_buffer.head].data, MAX_MESSAGE_LENGTH, format, args);
    va_end(args);

    msg_buffer.messages[msg_buffer.head].data[MAX_MESSAGE_LENGTH - 1] = '\0'; // Ensure null-termination

    msg_buffer.head = (msg_buffer.head + 1) % BUFFER_SIZE;
    msg_buffer.count++;
    return true;
}



void start_shell( void )
{
#if 1		//Test
	char msg[MAX_MESSAGE_LENGTH];


	initBuffer();
    initShellInterface();

    while(1)
    {
        runShellInterface(); /* Run the application shell */
        if( true == retrieveMessage(msg) )
        {
        	Ifx_Console_print( msg );
        }
    }
#else	//The code below will run in the freeRTOS environment, but it has a conflict between freeRTOS and shell functions because of sharing STM.
    initShellInterface();

    xTaskCreate( task_shell, "SHELL_TASK", configMINIMAL_STACK_SIZE, NULL, 0, NULL);
#endif

}
